# Generated by Django 3.2.12 on 2023-04-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('codcoment', models.AutoField(db_column='Codcoment', primary_key=True, serialize=False)),
                ('assunto', models.CharField(blank=True, db_column='Assunto', help_text='De maneira geral, do que trata o comentário?', max_length=255, null=True)),
                ('detalhe', models.CharField(blank=True, db_column='Detalhe', help_text='Descreva detalhes ...', max_length=255, null=True)),
            ],
            options={
                'db_table': 'coment',
                'ordering': ['assunto', 'detalhe'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('codtema', models.AutoField(db_column='Codtema', primary_key=True, serialize=False)),
                ('semana', models.SmallIntegerField(blank=True, db_column='Semana', null=True)),
                ('ordem', models.SmallIntegerField(blank=True, db_column='Ordem', null=True)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=15, null=True)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=255, null=True)),
                ('pagina', models.IntegerField(blank=True, db_column='Pagina', null=True)),
            ],
            options={
                'db_table': 'tema',
                'ordering': ['semana', 'ordem'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemaComent',
            fields=[
                ('codtema_coment', models.AutoField(db_column='Codtema_coment', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='Data', null=True)),
            ],
            options={
                'db_table': 'tema_coment',
                'ordering': ['tema', 'coment'],
                'managed': False,
            },
        ),
    ]
