# Generated by Django 3.2.12 on 2023-05-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ci',
            fields=[
                ('codci', models.CharField(blank=True, db_column='Codci', help_text='Nome do circuito integrado', max_length=15, primary_key=True, serialize=False)),
                ('semana', models.IntegerField(blank=True, db_column='Semana', null=True)),
                ('sobre', models.CharField(blank=True, db_column='Sobre', help_text='Sobre o circuito integrado', max_length=75, null=True)),
                ('pinagem', models.CharField(blank=True, db_column='Pinagem', help_text='Figura da pinagem do ci', max_length=25, null=True)),
            ],
            options={
                'db_table': 'ci',
                'ordering': ['semana'],
                'managed': False,
            },
        ),
    ]
